### ISSUE TITLE
USER STORY: Register an account

### ISSUE THREAD

**Issue by URiem** [URiem/pp4-ca#1]
As a **site user**, I can **enter personal information** so that **I can register a personal account**.

**Tasks:**
- [x] Implement registration form and functionality using allauth.
- [x] Customize styling.

**Acceptance criteria:**
- [x] User is able to create an account.
- [x] UX is appealing.
