### ISSUE TITLE
USER STORY: Site pagination

### ISSUE THREAD

**Issue by URiem** [URiem/pp4-ca#14]
As a **site user**, I can **access different pages on the site** so that **I can navigate smoothly through all the functionality of the site**.

**Task:**

- [ ] Set up distinct pages for different functionalities of the site.

**Acceptance Criteria:**

- [ ] Pages are displaying with intended functionality.
- [ ] Pages are designed with optimal UX in mind.
