### ISSUE TITLE
USER STORY: View travel log list

### ISSUE THREAD

**Issue by URiem** [URiem/pp4-ca#15]
As a **site user**, I can **view a list of travel logs** so that **browse and read featured content**.

**Task:**

- [ ] Display submitted logs as a list on the site.

**Acceptance Criteria**

- [ ] List of travel logs is displayed.
- [ ] Navigation is easy and UX is appealing.
