### ISSUE TITLE
USER STORY: Login

### ISSUE THREAD

**Issue by URiem** [URiem/pp4-ca#2]
As a **site user**, I can **use my account information** so that **I can log into my account**.

**Tasks:**
- [x] Implement login form and functionality using allauth.
- [x] Customize styling.

**Acceptance criteria:**
- [x] User is able to log into a personal account.
- [x] UX is appealing.
