### ISSUE TITLE
USER STORY: Log out

### ISSUE THREAD

**Issue by URiem** [URiem/pp4-ca#3]
As a **site user**, I can **log out of my account**, so that **my personal information is protected**.

**Tasks:**
- [x] Implement logout feature and functionality using allauth.
- [x] Customize styling.

**Acceptance criteria:**
- [x] User is able to log out of a personal account.
- [x] UX is appealing.
